// Menus Action Types
export const ADD_MENU = 'ADD_MENU';
export const CANCEL_MENU_EDIT = 'CANCEL_MENU_EDIT';
export const CLEAR_MENU = 'CLEAR_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const SET_MENU_LIST = 'SET_MENU_LIST';
export const SET_MENU = 'SET_MENU';
export const UPDATE_MENU_TITLE = 'UPDATE_MENU_TITLE';

// Menu Items Action Types
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const CANCEL_MENU_ITEM_EDIT = 'CANCEL_MENU_ITEM_EDIT';
export const CLEAR_MENU_ITEMS = 'CLEAR_MENU_ITEMS';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const SAVE_MENU_ITEMS = 'SAVE_MENU_ITEMS';
export const SET_MENU_ITEMS = 'SET_MENU_ITEMS';
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM';

// Employees Action Types
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const CANCEL_EMPLOYEE_EDIT = 'CANCEL_EMPLOYEE_EDIT';
export const CLEAR_EMPLOYEE = 'CLEAR_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SET_EMPLOYEE_LIST = 'SET_EMPLOYEE_LIST';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

// Timesheets Action Types
export const ADD_TIMESHEET = 'ADD_TIMESHEET';
export const CANCEL_TIMESHEET_EDIT = 'CANCEL_TIMESHEET_EDIT';
export const CLEAR_TIMESHEETS = 'CLEAR_TIMESHEETS';
export const DELETE_TIMESHEET = 'DELETE_TIMESHEET';
export const SAVE_TIMESHEETS = 'SAVE_TIMESHEETS';
export const SET_TIMESHEETS = 'SET_TIMESHEETS';
export const UPDATE_TIMESHEET = 'UPDATE_TIMESHEET';

export const NULL_ACTION = 'NULL_ACTION';
