version: '3'

services:
  # web:
  #   build: client
  #   ports:
  #     - 80:80
  backend:
    build: backend
    ports:
      - 4000:4000
    volumes:
      - app:/usr/src/app
  # postgres:
  #   image: postgres:11.1-alpine
  #   environment:
  #     POSTGRES_USER: expresso
  #     POSTGRES_DB: expresso
  #     POSTGRES_PASSWORD: thisisnotareallygoodpassword
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  app:
  # postgres:
