version: '3'

services:
  web:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./client/build:/usr/share/nginx/html
  backend:
    build: backend
    ports:
      - 4000:4000
    volumes:
      - app:/usr/src/app
  # postgres:
  #   image: postgres:11.1-alpine
  #   environment:
  #     POSTGRES_USER: expresso
  #     POSTGRES_DB: expresso
  #     POSTGRES_PASSWORD: thisisnotareallygoodpassword
  #   volumes:
  #     - postgres:/var/lib/postgresql/data

volumes:
  app:
  # postgres:
